### ISSUE TITLE
Make Options LP Deposits Transferable

### ISSUE THREAD

**Issue by avoyager** [YieldHand/OptionsMarketLiquidityPool#3]
We are working to create automated liquidity for options market for DeFi-based ERC20 tokens (https://www.yieldhand.com). You can learn more by visiting the site or by asking questions in the Discord (link at bottom of issue).

Users can deposit stablecoins, a withdrawal date is set by the owner, and in between we would like users to be able to transfer their holdings in ERC20 fashion before the withdrawal date so that the `poolOwnerBalance` is updated like balanceOf in an ERC20 transfer, so that when the withdrawal date comes, the appropriate people can withdraw their holdings.
This will require:
transfer, transferFrom, and approve functions

And 

Transfer and Approval events

Sound confusing or need clarification? 
We welcome you to join our Discord and ask questions: https://discord.gg/7fApFnA6qW

**Comment by juliof05** [comment]
Hi hello!!
